
language: objective-c
osx_image: xcode8.1

# cache: cocoapods
env:
global:
- LC_CTYPE=en_US.UTF-8
- LANG=en_US.UTF-8


before_install:
- env
- locale
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- pod --version
- pod setup --silent > /dev/null
- pod repo update --silent
- xcpretty --version
- xcodebuild -version
- xcodebuild -showsdks

script:
- set -o pipefail

- echo Check if the library described by the podspec can be built
- pod lib lint --allow-warnings

- echo Build
- xcodebuild clean build -workspace Example/DragNDrop.xcworkspace -scheme 'DragNDrop' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c

- echo Build the Demo apps
- xcodebuild clean build -workspace Example/DragNDrop.xcworkspace -scheme 'DragNDrop-Example' -configuration Debug -destination 'name=iPhone 6s' | xcpretty -c

- echo Run the tests
- xcodebuild test -workspace Example/DragNDrop.xcworkspace -scheme 'DragNDrop-Example' -configuration Debug -destination 'name=iPhone 6s' | xcpretty -c
